// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD17ryTiNPRfaOjJVxKnnSXZczUa6zLeY',
    appId: '1:173142091110:web:dc6331d8bc1cf1cc2854a7',
    messagingSenderId: '173142091110',
    projectId: 'skripsi-462c1',
    authDomain: 'skripsi-462c1.firebaseapp.com',
    storageBucket: 'skripsi-462c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEFWc18XgvTu0sC0a31K3DNoU_389Fd4U',
    appId: '1:173142091110:android:86150229ac1423812854a7',
    messagingSenderId: '173142091110',
    projectId: 'skripsi-462c1',
    storageBucket: 'skripsi-462c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuKPvZIh4GINTvlnSz2sId0x2jbExUjBc',
    appId: '1:173142091110:ios:dca34b63af9b16792854a7',
    messagingSenderId: '173142091110',
    projectId: 'skripsi-462c1',
    storageBucket: 'skripsi-462c1.firebasestorage.app',
    iosBundleId: 'com.example.aplikasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuKPvZIh4GINTvlnSz2sId0x2jbExUjBc',
    appId: '1:173142091110:ios:dca34b63af9b16792854a7',
    messagingSenderId: '173142091110',
    projectId: 'skripsi-462c1',
    storageBucket: 'skripsi-462c1.firebasestorage.app',
    iosBundleId: 'com.example.aplikasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD17ryTiNPRfaOjJVxKnnSXZczUa6zLeY',
    appId: '1:173142091110:web:400880beda8283e22854a7',
    messagingSenderId: '173142091110',
    projectId: 'skripsi-462c1',
    authDomain: 'skripsi-462c1.firebaseapp.com',
    storageBucket: 'skripsi-462c1.firebasestorage.app',
  );
}
